### ISSUE TITLE
Dialers using the `WithHTTPEndpoint` opt don't use the correct Useragent

### ISSUE THREAD

**Issue by kurtisvg** [GoogleCloudPlatform/cloud-sql-go-connector#157]
Likely related to the upstream TODO here: https://github.com/googleapis/google-api-go-client/blob/9d43e7dc08e2598d4dcb661324c4877dfd63c4f9/transport/http/dial.go#L40

**Comment by enocom** [comment]
Related to https://github.com/googleapis/google-api-go-client/issues/494.
