### ISSUE TITLE
Memory leak in Postgres  database/sql integration

### ISSUE THREAD

**Issue by stepan-romankov** [GoogleCloudPlatform/cloud-sql-go-connector#161]
## Bug Description

There is a memory leak in postgres/pgxv4/postgres.go:60 `func (p *pgDriver) Open(name string) (driver.Conn, error)`
This happens because `stdlib.RegisterConnConfig()` on every connection opening returns new dbURI and stores new instance of `pgx.ConnConfig` to map indexed by dbURI

## github.com/jackc/pgx/v4@v4.15.0/stdlib/sql.go
```go
func (d *Driver) registerConnConfig(c *pgx.ConnConfig) string {
	d.configMutex.Lock()
	connStr := fmt.Sprintf("registeredConnConfig%d", d.sequence)
	d.sequence++
	d.configs[connStr] = c
	d.configMutex.Unlock()
	return connStr
}

```
## How to reproduce
1. Code
```go
creds, _ := google.FindDefaultCredentials(ctx, sqladmin.SqlserviceAdminScope)
_, _ = RegisterDriver("cloud-sql", cloudsqlconn.WithIAMAuthN(), cloudsqlconn.WithTokenSource(creds.TokenSource))
pgClient, err := sql.Open("cloud-sql", "host=... user=... dbname=... sslmode=disable")
pgClient, err := sql.Open("cloud-sql", "host=... user=... dbname=... sslmode=disable")
```
2. Check Driver.configs (github.com/jackc/pgx/v4@v4.15.0/stdlib/sql.go:227), there are 2 entries and map is growing on every new connection.

**Comment by enocom** [comment]
Thanks for the report @stepan-romankov. I''ll work on a fix soon.

**Comment by stepan-romankov** [comment]
Always welcome @enocom, and thank for the quick feedback!
