### ISSUE TITLE
Cloud Function Deployment Build Error 

### ISSUE THREAD

**Issue by wk93210** [GoogleCloudPlatform/cloud-sql-go-connector#257]
## Bug Description

When using `cloud-sql-go-connector` as a dependency in vendor, can't run `gcloud functions deploy` due to build errors from `cloud-sql-go-connector`

## Example code (or command)

\<file\>.go
```go
package <pkg>

import (
    "cloud.google.com/go/cloudsqlconn"
)

// ...
```

go.mod
```go
module github.com/<some>/<repo>

go 1.16

require (
	cloud.google.com/go/cloudsqlconn v0.5.0
)
```

Install as vendor
```bash
go mod vendor
```

Upload to Cloud Function
```bash
gcloud functions deploy <Func> \
    --quiet \
    --entry-point <Func> \
    --trigger-http  \
    --region us-central1 \
    --runtime go116 \
    --env-vars-file .env.production
```

## Stacktrace
```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: src/<some>/<repo>/vendor/github.com/<other>/<repo>/<path>/<file>.go:11:2: /workspace/src/<some>/<repo>/vendor/cloud.google.com/go/cloudsqlconn/doc.go:1: cannot parse import comment; Error ID: 2f5e35a0
```

## How to reproduce

1. Put cloudsqlconn in go.mod
2. Run `go mod vendor`
3. Import cloudsqlconn in some code
4. use `gcloud functions deploy` to deploy the code

## Environment

1. OS type and version:Description:  `Ubuntu 22.04 LTS`
5. Go version:  `go1.16.15 linux/arm64`
3. Connector version: v0.5.0

**Comment by enocom** [comment]
Thanks @wk93210. We can probably just remove all these `doc.go` files as modules makes the import path restriction unnecessary.

**Comment by enocom** [comment]
To unblock your deployment, you can install the latest commit with this command:

``` shell
go get cloud.google.com/go/cloudsqlconn@bc57877f16a61e42c603d4dc50ff4d01fc01d9d9
```

**Comment by wk93210** [comment]
Thank you so much! @enocom
