### ISSUE TITLE
Feature Request: Add sqlcomment (GCP SQL Insights) support 

### ISSUE THREAD

**Issue by StevenACoffman** [GoogleCloudPlatform/cloud-sql-go-connector#272]
## Feature Description
@enocom While #32 Added initial support for tracing via OpenCensus and we can use the [OpenTelemetry bridge](https://github.com/open-telemetry/opentelemetry-go/tree/main/bridge/opencensus). This allows `otel` telematics to be exported as either traces (spans) or as metrics to Cloud Trace / StackDriver endpoints.

I read that [Sqlcommenter merged into OpenTelemetry](https://cloud.google.com/blog/products/databases/sqlcommenter-merges-with-opentelemetry).

[Sqlcommenter](https://google.github.io/sqlcommenter/) works on the driver/ORM layer, by injecting metadata containing _comments_ as part of the SQL statements that are sent to the database. These logs are then ingested on the database side (with support from [Cloud SQL Insights](https://cloud.google.com/blog/products/databases/get-ahead-of-database-performance-issues-with-cloud-sql-insights), a proprietary Google Cloud offering).

I would like [cloud-sql-go-connector](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector) driver to add the *de facto* standardized fields `traceparent` and `tracestate` to the SQL as comments sent to the database. For example:
```
select * from widgets /*traceparent='00-5bd66ef5095369c7b0d1f8f4bd33716a-c532cb4098ac3dd2-01',tracestate='congo%3Dt61rcWkgMzE%2Crojo%3D00f067aa0ba902b7'*/
```
I'd like to be able to use both [Cloud SQL Insights](https://cloud.google.com/blog/products/databases/get-ahead-of-database-performance-issues-with-cloud-sql-insights) and [Cloud Trace](https://cloud.google.com/trace) in my application, and I think [cloud-sql-go-connector](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector) is the best place to do it.

## Alternatives Considered
I can use https://github.com/jbub/sqlcommenter or https://github.com/ucarion/sqlcommenter to wrap my driver that I already wrap for cloud-sql-go-connector. 

## Additional Context
Feature Request: Open Telemetry Support for CloudSQL Go Connector #115

**Comment by enocom** [comment]
Thanks for the detailed feature request @StevenACoffman. I'll need to spend some time looking at our options. Right now the connector doesn't understand the bytes going back and forth to Cloud SQL, and so we don't have a mechanism to insert comments into SQL statements.

**Comment by StevenACoffman** [comment]
Added as Feature Request here: https://issuetracker.google.com/issues/241261093

**Comment by enocom** [comment]
Going to close this. For now the Connector doesn't have protocol awareness and so couldn't annotate SQL statements.
