### ISSUE TITLE
Add custom driver implementation import hooks

### ISSUE THREAD

**Issue by kurtisvg** [GoogleCloudPlatform/cloud-sql-go-connector#3]
Add some custom "sql" drivers that help call the dialer for user's that don't need customization.

Examples: https://github.com/GoogleCloudPlatform/cloudsql-proxy/tree/main/proxy/dialers

**Comment by kurtisvg** [comment]
Frustratingly enough, the mysql and postgres hooks both rely on different methods to do this: 

The [MySQL hook](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/dfd5bcc4507e7a0902eb8d1082d8c9055a2ed462/proxy/dialers/mysql/hook.go#L30) uses a driver specific [`mysql.RegisterDialContext`](https://pkg.go.dev/github.com/go-sql-driver/mysql#RegisterDialContext)

The [Postgres hook](https://github.com/GoogleCloudPlatform/cloudsql-proxy/blob/dfd5bcc4507e7a0902eb8d1082d8c9055a2ed462/proxy/dialers/postgres/hook.go#L35) registers a custom [`sql/Driver`](https://golang.org/pkg/database/sql/driver/#Driver) object as a "cloudsqlpostgres" driver.

**Comment by kurtisvg** [comment]
Pgx just uses whatever [`DialFunc`](https://pkg.go.dev/github.com/jackc/pgconn#DialFunc) is specified by the [Config](https://pkg.go.dev/github.com/jackc/pgconn#Config).

I'm not really sure it makes sense to keep implementing these hooks - seems like it's easier to allow the user to just specify it in anything but `lib/pq`, which is in maintenance mode. It's probably clearer to provide per-driver instructions for specifying the connect functions.

**Comment by enocom** [comment]
> It's probably clearer to provide per-driver instructions for specifying the connect functions.

I think this is the right thing to do for our initial release. Based on demand, we can revisit this decision in the future.

**Comment by StevenACoffman** [comment]
Hi! So I wonder if you can add a pgx example?

**Comment by kurtisvg** [comment]
@StevenACoffman there is an example using pgx in the README: https://github.com/kurtisvg/cloud-sql-go-connector#pgx-for-postgres

**Comment by StevenACoffman** [comment]
Ah, great! Is there an estimate when this will be production ready?

**Comment by kurtisvg** [comment]
@StevenACoffman Which work are you specifically referring to? This dialer should largely cover everything that the Cloud SQL proxy does for connecting directly from an application. Our goal is to have this GA within the next couple of months. I expect it to be largely stable at this point.

**Comment by enocom** [comment]
Bumping this back to a p1.

Here's what I'm thinking this issue involves:

- Add an example to the README of creating a sql.DB type using:
  - the connector and pgx
  - the connector and Go MySQL Driver
  - The connector and go-mssqldb
- Link to the Go sample code which includes yet another example of the above
- Provide hooks for Postgres, MySQL, and SQL Server using the most popular driver for each engine (pgx, Go MySQL Driver, and go-mssqldb) to enable frictionless usage of GORM.
- Send a PR to update the GORM documentation once the new hooks are available

**Comment by StevenACoffman** [comment]
@kurtisvg  FWIW, I have been watching the improvements to the sql-proxy, like "fix: increase rateLimit burst size to 2", "allow multiple instances", "add support for specifying a quota project", "add support for ReadTime requests in Admin API" and wondered if the lack of corresponding updates here was a sign that a different direction had been taken.

**Comment by enocom** [comment]
We'll be adding any relevant features to the connector here, especially ReadTime support. The other items you've noted will either appear in the v2 proxy or are patches over various problems in the existing proxy.

**Comment by enocom** [comment]
Completed in #70 and #71.

**Comment by enocom** [comment]
I'll send a PR to update the Gorm docs when the connector is GA.

https://gorm.io/docs/connecting_to_the_database.html#Customize-Driver-1

**Comment by enocom** [comment]
https://github.com/go-gorm/gorm.io/search?p=1&q=cloudsql
