### ISSUE TITLE
Add support for pgx v5 in postgres package

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/cloud-sql-go-connector#335]

**Comment by enocom** [comment]
https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/394

**Comment by jorgerasillo** [comment]
Hi @enocom ,
any idea when this would be?

Background: We moved away from using pgx v4 to gain some of the advantages of using v5, and are stuck with v4 now. Internally, we're looking to possibly fork the connector in the interim while this is ready because we would like to remove the cloudsql proxy from the main path.

**Comment by enocom** [comment]
@jorgerasillo There's a minor change I need to make to the Dialer type to support pgv5 generally. I'll put a PR up for that change soon (details in https://github.com/jackc/pgx/issues/1413).

Once that's done, there's actually nothing stopping you from copying and adapting https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/main/postgres/pgxv4/postgres.go but instead use pgv5. This issue is for providing a convenience wrapper, which we can't do anytime soon given pgxv5 doesn't support older Go versions.

I can add some example code here if that would help.

**Comment by jorgerasillo** [comment]
yeah I think I know what needs to be done, but would take the example code too :) 

PS. Thanks for putting this together!

**Comment by enocom** [comment]
Here's the change that will unblock using the dialer with pgx v5: https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/417.

If you were to write your own wrapper (since we can't release without Go 1.16 support), it would look like this (basically identical to pgxv4 but with a different import):

``` golang
package pgxv4

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"net"
	"sync"

	"cloud.google.com/go/cloudsqlconn"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/stdlib"
)

func RegisterDriver(name string, opts ...cloudsqlconn.Option) (func() error, error) {
	d, err := cloudsqlconn.NewDialer(context.Background(), opts...)
	if err != nil {
		return func() error { return nil }, err
	}
	sql.Register(name, &pgDriver{
		d:      d,
		dbURIs: make(map[string]string),
	})
	return func() error { return d.Close() }, nil
}

type pgDriver struct {
	d  *cloudsqlconn.Dialer
	mu sync.RWMutex
	// dbURIs is a map of DSN to DB URI for registered connection names.
	dbURIs map[string]string
}

func (p *pgDriver) Open(name string) (driver.Conn, error) {
	var (
		dbURI string
		ok    bool
	)

	p.mu.RLock()
	dbURI, ok = p.dbURIs[name]
	p.mu.RUnlock()

	if ok {
		return stdlib.GetDefaultDriver().Open(dbURI)
	}

	p.mu.Lock()
	defer p.mu.Unlock()
	// Recheck to ensure dbURI wasn't created between locks
	dbURI, ok = p.dbURIs[name]
	if ok {
		return stdlib.GetDefaultDriver().Open(dbURI)
	}

	config, err := pgx.ParseConfig(name)
	if err != nil {
		return nil, err
	}
	instConnName := config.Config.Host // Extract instance connection name
	config.Config.Host = "localhost"   // Replace it with a default value
	config.DialFunc = func(ctx context.Context, _, _ string) (net.Conn, error) {
		return p.d.Dial(ctx, instConnName)
	}

	dbURI = stdlib.RegisterConnConfig(config)
	p.dbURIs[name] = dbURI

	return stdlib.GetDefaultDriver().Open(dbURI)
}
```

**Comment by jorgerasillo** [comment]
The example code above seems like it should be used if we were using the [`database/sql`](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector#postgres-1) package, which we're not. 

We're currently using IAM AuthNZ and using pgxpool to connect, this example [here](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector#postgres-1) is closer to what I would expect, however, the example shows a connection string that includes user/password authentication which is not what we want, our connection string looks like: 
```sh
postgres://user@host:port/<db_name>?search_path=<schema_name>
```

I suspect that I'll need to tweak this setup a bit, but I'll have more info later this afternoon when I try this setup.

**Comment by enocom** [comment]
Oh I see. If you're using pgxpool directly, then you only need to update the version and should be good. Note that the fix in #417 will be released next month, so you might have to pin to a recent SHA until that's out.

**Comment by jorgerasillo** [comment]
that's working great, thank you!

**Comment by enocom** [comment]
Build flags don't work for dependencies unfortunately. So until we drop support for old versions of Go, the best option is probably to copy the code from https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/issues/335#issuecomment-1358095212 and use that as a hook in gorm.

**Comment by enocom** [comment]
And it's also possible to override this library's v4 dep with a go.mod replace directive if necessary.

**Comment by Mistic92** [comment]
Can you provide example how to do that and use with gorm?

**Comment by enocom** [comment]
That seems like a good thing to add somewhere. Let me figure it out and post here to start.

**Comment by Mistic92** [comment]
I'm trying to use IAM Database Auth for Postgres to connect from Cloud Run but I can't make it work.
