### ISSUE TITLE
Can one use IAM auth with Private IP at the same time?

### ISSUE THREAD

**Issue by liufuyang** [GoogleCloudPlatform/cloud-sql-go-connector#381]
## Question
Can one use IAM auth with Private IP at the same time?

This is how we set the client up at the moment. But does this `cloudsqlconn.WithPrivateIP()` option will really config the library to use private IP as the connection?
```golang
    options := make([]cloudsqlconn.Option, 0, 0)
    options = append(options, cloudsqlconn.WithIAMAuthN())
    if usePrivateIP {
        options = append(options, 
        cloudsqlconn.WithDefaultDialOptions(cloudsqlconn.WithPrivateIP()))
    }
    cleanup, err := pgxv4.RegisterDriver(driver, options...)
    ...
    db, err := sql.Open(driver, connStr)
```

Or, even with code like this, in practice, the client still connects via external IP + proxy?

The code for us runs in CloudRun, we have also setup the VPC for the sql instance.

If the above setup can work, do you how could we easily test/verify it uses private ip?

And if the above code works, can we also set up it like this?
```golang
cleanup, err := pgxv4.RegisterDriver(driver, cloudsqlconn.WithDefaultDialOptions(
		cloudsqlconn.WithPrivateIP(),
		cloudsqlconn.WithDialIAMAuthN(true),
	))
```

Wasn't quite sure what is the difference between an `Option` and a `DialOption` there.

Thank you very much.

## Additional Context

We are doing this because we have a db instance in Europe and a cloud run instance in US, and some times we get a dial refresh error. We read the [Google docs](https://cloud.google.com/sql/docs/postgres/connect-overview)
saying that the private IP can have lower latency and perhaps more stable network. So we are trying to use the instance's private ip and at the same time still use cloud-sql-connector to handle the IAM user login.

**Comment by enocom** [comment]
@liufuyang both approaches should work.

In short, `Option` is a type for configuring a dialer generally and `DialOption` is for configuring a particular call of `Dial`. Sometimes, it's useful to configure default `DialOption` -- like in your case where you always want to use private IP).

**Comment by liufuyang** [comment]
Aha thank you, that is good to know.

And this also means with private ip, the IAM auth can still work as before, right?

**Comment by enocom** [comment]
Yes, The private IP is just to require callers to specify which address the dialer connects to. IAM AuthN works either way.

**Comment by liufuyang** [comment]
Thank you very much 👍
