### ISSUE TITLE
refresh failed: context deadline exceeded

### ISSUE THREAD

**Issue by liufuyang** [GoogleCloudPlatform/cloud-sql-go-connector#384]
## Bug Description

As previously stated on https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/issues/381 and https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/issues/370,
we see this error from time to time:

```
rpc error: code = Internal desc = database read error: failed to connect to `host=localhost user=xxx@xxx.iam database=db`: dial error (timeout: refresh failed: context deadline exceeded)
```

And when it happens, the service seems keep being in this "error state" once in a while.

This graph shows how often it could happen for us:
![image](https://user-images.githubusercontent.com/161689/201371548-ccc8b62c-2725-4ef0-82ab-3851926917b6.png)

## Example code (or command)

How we setup the connection:
```go
        driver := "cloudsql-postgres"

	options := make([]cloudsqlconn.Option, 0)
	options = append(options, cloudsqlconn.WithIAMAuthN())
	options = append(options, cloudsqlconn.WithDefaultDialOptions(cloudsqlconn.WithPrivateIP()))

	cleanup, err := pgxv4.RegisterDriver(driver, options...)
	if err != nil {
		return nil, nil, fmt.Errorf("could not register CloudSQL driver: %w", err)
	}

	dbHost := fmt.Sprintf("%s:%s:%s", cfg.CloudSQL.GCPProject, cfg.CloudSQL.DBRegion, cfg.CloudSQL.InstanceName)
	dbUser := strings.TrimSuffix(cfg.CloudSQL.User, ".gserviceaccount.com")
	connStr := fmt.Sprintf(
		"host=%s user=%s dbname=%s sslmode=disable",
		dbHost,
		dbUser,
		cfg.CloudSQL.DBName,
	)

	db, err := sql.Open(driver, connStr)
	db.SetMaxOpenConns(2)
	db.SetMaxIdleConns(2)
	db.SetConnMaxLifetime(time.Hour)
...
```

## Stacktrace

We don't have strackrace available now but we logged the context deadline before the code calls onto db to do a simple read. This is what we could see:
```
ctx deadline left before calling db: 9962 ms
```
So this means there is around 10s still available but then the call to db failed with 

> failed to connect to `host=localhost user=xxx@xxx.iam database=db`: dial error (timeout: refresh failed: context deadline exceeded)

## How to reproduce
That is difficult to say. Run a long-running service, randomly do simple db read, this shows up from time to time

## Environment

1. OS type and version: google Cloudrun
2. Go version: `go version` v1.19.3
2. Connector version: v1.0.1

---

Thank you, and if you need any other info we could provide, let us know.

**Comment by enocom** [comment]
Thanks for the bug report @liufuyang. This might be related to how Cloud Run throttles the CPU when the service goes to sleep. We've made some improvements in the Java connector that we can probably make here as well.

Does your Cloud Run service scale to 0?

**Comment by liufuyang** [comment]
Thank you for the feedback. We used to have minscale set as 0 but for dealing with this issue we have previously set minscale as 1 (still one for now) but it seems not fully resolving it (maybe it reduces the frequency I am not sure).

But we haven't tested with turning of the CPU throttling yet. It has always been on. We were thinking if we turn it off, it bring some extra cost, but I guess we can give it a try as well.

**Comment by liufuyang** [comment]
We have turned off the CPU throttling for about a week, and during this time we never saw this `timeout: refresh failed` anymore. So perhaps it could be related to missing improvements in Java as mentioned by @enocom above.

Not sure if you want to close this issue but perhaps it would be nice if we could have similar improvements in this go package. As we have other system/components running on CloudRun with postgres, and those do not have lots of traffic so turning off CPU throttling for them will increase our costs a lot.

We also tried to keep the CloudRun minScale to 1, not 0, but it didn't really help with this specific issue.

Let me know what you prefer, I can either close this or rename it as something like 
> Adding improvements for  Cloud Run throttles the CPU (similar with Java connector)

Thank you.

**Comment by enocom** [comment]
Thanks for the update @liufuyang. I'm mistaking minScale for CPU throttling. And we can leave this open.

**Comment by enocom** [comment]
So one option would be adding support for a refresh option that changes all refreshes to be lazy. This would increase connection latency but would at least allow clients to have a way to avoid these CPU throttling issues.

**Comment by liufuyang** [comment]
To add some info here, it seems my previous message saying "Turning off CPU throttling then don't see this error anymore" was not that true. This error still can come from time to time. For now, we had to use a k8s liveness probe to keep an endpoint to constantly check on the DB connection, and if this happens let k8s kill the pods so as to restart the DB connections.

This is probably not ideal for us but it at least keeps our alerts from firing. It would be nice if we could solve it in a good way so we don't have to rely on the pod restarting? 🤔

**Comment by enocom** [comment]
Are you seeing this same issue in Kubernetes? I was thinking this was a problem with how Cloud Run throttles the CPU...

**Comment by liufuyang** [comment]
Sorry, when I said k8s I actually meant CloudRun. (I could be wrong but I view CloudRun some sort of managed k8s under the hood as many configurations are the same, such as the liveness probe.)

We do see this with CloudRun and now we think it might not that related to CPU throttling, but we are not sure, as it seemed less issue when turning off CPU throttling, but it didn't solve it by turning it off.

**Comment by jorgerasillo** [comment]
we have actually been testing this in a production environment in k8s and have seen this same behavior but haven't been able to track down cause yet.

Here's what our environment looks like:
- kubernetes
- cloud sql connector: v1.1.1
- pgx/v5 v5.2.1-0.20221221021826-29ad306e47c4

**Comment by benweint** [comment]
Adding on to @jorgerasillo's comment, here are a few more details about the issue we saw that looked like this same symptom.

For context: we're currently testing out the Go connector as a replacement for the CloudSQL proxy running as a sidecar. In the testing setup, we have a single canary instance running the connector, while other instances continue to use the proxy. During an incident last week, we saw that the canary instance using the connector experienced repeated request failures of this sort (the CloudSQL proxy-based instances have seen no similar behavior):

```
time="2023-01-26T17:23:54Z" level=warning msg="Error dialing: refresh failed: context deadline exceeded"
time="2023-01-26T17:23:54Z" level=warning msg="internal server error: failed to connect to `host=/tmp user=<redacted> database=<redacted>`: dial error (refresh failed: context deadline exceeded)"
```

These errors continued for a period of about 10 minutes, at which point the canary instance seemed to recover spontaneously without intervention. You can see the overall timeline reflected in this chart of calls to the CloudSQL Admin API in our project:

![image](https://user-images.githubusercontent.com/982820/215845430-3d613895-6a33-4acb-b6bc-08a6b62fb33f.png)

Note that the API calls begin ~5 minutes *before* the onset of the errors at the application layer, suggesting to me that the connector was behaving as intended in trying to refresh the instance info ~5 minutes prior to its expiry time. My reading of the behavior that follows is that it repeatedly failed to do so, trying about once every 30s and timing out until it eventually was successful.

Is there anything we could do to capture more detailed information about when and why refreshes are failing like this that might help diagnose this issue?

**Comment by enocom** [comment]
Thanks for all the extra info folks. Let me spend some time with this and see what's going on here. I'll report back here.

**Comment by liufuyang** [comment]
@enocom Thanks for the effort on this, I updated this issue's title, let me know if that fits better.

**Comment by enocom** [comment]
Sorry for the slow response here.

Inside our refresh code, we have a single context with a timeout: https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/main/internal/cloudsql/refresh.go#L309.

If we're seeing the error `refresh failed: context deadline exceeded`, it means that context is timing out while waiting for Admin API calls to complete. By default, the timeout is set to 30 seconds. It seems surprising that the Admin API could not complete an HTTP response in 30 seconds. What might be happening is that the CPU is either throttled (as in Cloud Run) or maxed out (as in GKE).

The GKE angle is easier to debug. So let's start there and then return to Cloud Run. When you see the GKE error, what kind of CPU usage do you see for the Proxy? Typically we recommend 1 CPU and 2 GiB of memory, but throughput and number of connections will affect those numbers.

Finally, the Go Connector supports tracing. It would be very helpful to capture one of these context deadline exceeded errors in a trace. That would provide some strong evidence towards the root cause. See https://github.com/GoogleCloudPlatform/cloud-sql-go-connector#enabling-metrics-and-tracing.

Meanwhile, I'll try to reproduce this myself.

**Comment by liufuyang** [comment]
Thank you for investigating this. For the CloudRun side, I can confirm that it has no impact by turning on or off the CPU-throttling option. For now, we have CPU-throttling as off and this shows up quite often.

To test it on your side could be quite easy as well, I believe all you need to do is to set up a CloudSQL and then keep a service running with this connector (I think you might need to turn on `WithIAMAuthN` option) and constantly do `db.ping()` (that is what our liveness probe doing) and from time to time you should see `db.ping()` start to fail continuously.

Another question is do you think this config would matter on how often the refresh (to the Admin API) happens?
```
db.SetConnMaxLifetime(5 * time.Minute)
```
If it could be related we can also try to increase it and see if there is any difference.

**Comment by benweint** [comment]
>When you see the GKE error, what kind of CPU usage do you see for the Proxy? Typically we recommend 1 CPU and 2 GiB of memory, but throughput and number of connections will affect those numbers.

That error arose during a time when we were using the connector, not the proxy. In general, though, we see CPU usage for the proxy being consistently <30% of quota (set to 1 core), usually closer to 10%.

During the timeframe of the incident I included logs from on 1-26-2023 when we were using the connector, CPU usage for the application container (housing both the application code and the connector) was < 0.4 cores (out of a quota of 2 cores).

So, this is consistent with @liufuyang's observation that CPU throttling doesn't seem to explain the Admin API timeout.

>Finally, the Go Connector supports tracing. It would be very helpful to capture one of these context deadline exceeded errors in a trace. That would provide some strong evidence towards the root cause. See https://github.com/GoogleCloudPlatform/cloud-sql-go-connector#enabling-metrics-and-tracing.

Sounds good, we will see if we can get tracing hooked up!

(As an aside, we noticed that the library is currently using OpenCensus, which has been folded into the OpenTelemetry project - are there plans to migrate the instrumentation to OpenTelemetry instead?)

**Comment by enocom** [comment]
Thanks @benweint. We use the Go Connector internally where there is significant tooling around OpenCensus and so that's forced our hand. There is a OpenCensus Bridge that lets you send OpenCensus metrics and traces to OpenTelemetry. See https://github.com/open-telemetry/opentelemetry-go/blob/main/bridge/opencensus/README.md.

As much as I'd love to use Open Telemetry, metrics support is alpha, which makes it hard for us to expose a stable API. So for now, it's OpenCensus.

**Comment by benweint** [comment]
Cool, I figured it might be something like that. Thanks for the background @enocom! We can work with OpenCensus for now.

**Comment by liufuyang** [comment]
Thanks a lot, I was just about to ask whether it could be related to the rate limiter as the "only context" was thrown into the wait methods of the limiter immediately after the context was created :)

**Comment by liufuyang** [comment]
After using the patched version for a week, haven't seen another error like this for 7 days. I can say this is solved :) Thank you very much again for providing good help on this 👍

**Comment by enocom** [comment]
That's good to hear. As usual, feel free to open an issue if you see something not working well.

**Comment by enocom** [comment]
FWIW we finally added support for a lazy refresh too. https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/pull/772
