### ISSUE TITLE
Use HandshakeContext when possible

### ISSUE THREAD

**Issue by benpbrown** [GoogleCloudPlatform/cloud-sql-go-connector#409]
## Feature Description

When performing an explicit TLS handshake, use the [HandshakeContext](https://pkg.go.dev/crypto/tls#Conn.HandshakeContext) method introduced in Go 1.17 instead of [Handshake](https://pkg.go.dev/crypto/tls#Conn.Handshake). The difference is that `HandshakeContext` will respect context deadlines or cancelation.

In a previous iteration of this connector (cloud-sql-proxy), we an issue where Handshake could hang for minutes (like five minutes): https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/986.

## Alternatives Considered
I am not able to come up with a workaround as the standard library method `Handshake` is not cancelable (so the goroutine is hung no matter what we do).

## Additional Context
Equivalent fix in cloud-sql-proxy: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/pull/987
Handshake line in this repo: https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/2a88f2399cb569b04a2e898afae82b79b984cdee/dialer.go#L231

**Comment by enocom** [comment]
Sorry for missing this @benpbrown. I can port the same fix to the connector here.
