### ISSUE TITLE
Add support for impersonating an account

### ISSUE THREAD

**Issue by enocom** [GoogleCloudPlatform/cloud-sql-go-connector#46]
Context https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/417.

**Comment by liufuyang** [comment]
So any update on this? We are using this tool to run a backend service that uses a SA(also as an IAM db user) to a CloudSQL postgress.

What could be a good way at the moment to allow me to run the service locally and impersonate myself's google account as the SA that the backend uses in production?

**Comment by enocom** [comment]
I learned recently that is already support with this:

https://pkg.go.dev/google.golang.org/api@v0.94.0/impersonate

In short, make a token source as you wish and use the [WithTokenSource](https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/main/options.go#L102-L104) option to use it.

**Comment by enocom** [comment]
@liufuyang Let me know if the impersonate package does what you're looking for.
