### ISSUE TITLE
Improve documentation for Auto IAM AuthN usage

### ISSUE THREAD

**Issue by benguild** [GoogleCloudPlatform/cloud-sql-go-connector#563]
### Bug Description

https://stackoverflow.com/questions/76472486/connecting-to-postgres-cloud-sql-from-app-engine-standard-with-iam-is-timing-out

I'm not sure what's going on here, but I've tried multiple sample codes and it always says the IAM password is wrong.

Using a username/password that I configure for the instance **does** work, and using IAM via Cloud SQL Proxy from my client machine also **does** work.

### Example code (or command)

```Go
import (
    "database/sql"
    "fmt"
    "net"

    "cloud.google.com/go/cloudsqlconn"
    pgx "github.com/jackc/pgx/v4"
    pgxStdlib "github.com/jackc/pgx/v4/stdlib"
)

func test() {
    var dialOptions []cloudsqlconn.DialOption

    if usePrivateIP {
        dialOptions = append(dialOptions, cloudsqlconn.WithPrivateIP())
    }

    var dialer *cloudsqlconn.Dialer
    dialer, err := cloudsqlconn.NewDialer(
        context.Background(),
        cloudsqlconn.WithIAMAuthN(),
        cloudsqlconn.WithDefaultDialOptions(dialOptions...),
    )

    if err != nil {
        return
    }

    config, err =: pgx.ParseConfig(fmt.Sprintf(
        "user=%s password=%s database=%s",
        user,
        password,
        databaseName,
    ))

    if err != nil {
        return
    }

     config.DialFunc = func(ctx context.Context, _ string, _ string) (net.Conn, error) {
        return dialer.Dial(ctx, instanceName)
    }

    var db *sql.DB
    db, err := sql.Open("pgx", pgxStdlib.RegisterConnConfig(config))

    if err != nil {
        return
    }

    _ = db // should be live
}
```

### Steps to reproduce?

1. Try to connect
2. Cry and then switch back to username and password, from IAM App Engine Standard principal user and no password

### Environment

1. OS type and version: App Engine Standard
2. Go version: 1.20
3. Cloud SQL Go Connector version: v1.2.2

**Comment by enocom** [comment]
Thanks, @benguild. Let me spin up a test app to confirm this path actually works and then I'll update here with details.

**Comment by enocom** [comment]
So I just threw together a toy app on App Engine and it worked. There's a configuration error in your setup that we need to find.

Here's what I did:

1. Ensured my database has the `cloudsql.iam_authentication` flag set to on
2. Ensured my associated service account is a user in the db (e.g., `214833905528-compute@developer`). Note: App Engine doesn't use the Compute Service account by default and instead uses an appspot account. You'll need to check which account you're using and line it up (database user + app engine)
3. Deployed the following code:

``` golang
package main

import (                                                                                                                       
        "context"      
        "database/sql"                                         
        "fmt"
        "log"                                                  
        "net"                                                  
        "net/http"                                                                                                             
        "os"                                                   
        "time"
                               
        "cloud.google.com/go/cloudsqlconn"
        "github.com/jackc/pgx/v4"
        "github.com/jackc/pgx/v4/stdlib"
)

func timeHandler(db *sql.DB) func(http.ResponseWriter, *http.Request) {
        return func(rw http.ResponseWriter, _ *http.Request) {
                row := db.QueryRow("select now()")
                var t time.Time
                if err := row.Scan(&t); err != nil {
                        log.Printf("failed to read from db: %v", err)
                        rw.WriteHeader(500)
                        fmt.Fprintf(rw, `{"error":"%v"}`, err)
                        return
                }
                fmt.Fprintf(rw, `{"time":"%v"}`, t)
        }
}

func withDefaultPort(p string) string {
        if p != "" {
                return p
        }
        return "8080"
}

func main() {
        var dialer *cloudsqlconn.Dialer
        dialer, err := cloudsqlconn.NewDialer(
                context.Background(),
                cloudsqlconn.WithIAMAuthN(),
        )
        if err != nil {
                return
        }
        user := "214833905528-compute@developer" // FIXME: change this to match your actual SA

        config, err := pgx.ParseConfig(fmt.Sprintf("user=%s database=postgres", user))
        if err != nil {
                log.Fatalf("failed to parse config: %v", err)
        }

        config.DialFunc = func(ctx context.Context, _ string, _ string) (net.Conn, error) {
                return dialer.Dial(ctx, "enocom-playground:us-central1:pg")
        }

        db, err := sql.Open("pgx", stdlib.RegisterConnConfig(config))
        if err != nil {
                log.Fatalf("failed to open DB: %v", err)
        }
        http.HandleFunc("/", timeHandler(db))
        p := withDefaultPort(os.Getenv("PORT"))
        if err := http.ListenAndServe(":"+p, nil); err != nil {
                log.Printf("failed to start server: %v", err)
        }
}
```

My SA has Cloud SQL Client and Cloud SQL instance user roles on it.

Let me know if this helps.

**Comment by benguild** [comment]
> Here's what I did:
> ...
> 2. Ensured my associated service account is a user in the db (e.g., `214833905528-compute@developer`). ...
> ...
> Let me know if this helps.

@enocom So I took a look at your comment and what immediately stood out to me was that you use `214833905528-compute@developer` rather than the full IAM Service Account (`214833905528-compute@developer.gserviceaccount.com`) address.

As soon as I truncated that, everything worked perfectly.

So, I'm glad this is figured out... so that the documentation can be updated to highlight the difference here and save other folks hours/days, as it's unclear that this must be truncated and the values aren't interchangeable. Especially since the Cloud SQL Proxy client does this automatically.

**Comment by benguild** [comment]
Thank you for your help on this.

**Comment by benguild** [comment]
I'm going to leave this open (feel free to close) so that this can be considered for an update to the docs.

**Comment by enocom** [comment]
Sounds good. We’ll see how to make this crystal clear for others.

**Comment by jackwotherspoon** [comment]
@enocom In the Cloud SQL Python Connector README, I have an [IAM Authentication section](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector/blob/main/README.md#iam-authentication) that mentions the formatting rules for the `user` param when using the Connector with IAM AuthN. Maybe we can add a similar section to the README of this repo.

**Comment by jackwotherspoon** [comment]
@benguild do you remember which Google Cloud docs page you were using as reference? I can make sure the appropriate docs get updated as well, thanks! 😄

**Comment by benguild** [comment]
I'm not sure of all of them but this one in particular says: "By default, your app will authorize your connections using an App Engine service account. The service account identity is in the format `PROJECT_ID@appspot.gserviceaccount.com`"

https://cloud.google.com/sql/docs/postgres/connect-app-engine-standard

That may be the format of the actual service account, but we know that changes when it's attached to the instance.

**Comment by jackwotherspoon** [comment]
In addition to the above PR I filed an internal bug to update our docs pages with additional details for formatting IAM AuthN users when connecting via Proxy or a Connector
