### ISSUE TITLE
"Failed to get instance metadata" error while connection to CloudSQL

### ISSUE THREAD

**Issue by MarkShleiferCinemo** [GoogleCloudPlatform/cloud-sql-go-connector#718]
### Bug Description

Hi, we're experiencing a weird behavior while trying to connect CloudSQL using your library.

Once in a while, when pods restart, there is an error while trying to connect to the CloudSQL instance:
```
failed to get instance: Refresh error: failed to get instance metadata (connection name = "<some_connection_name>"): Get "https://sqladmin.googleapis.com/sql/v1beta4/projects/<my_project>/instances/<my_instance>/connectSettings?alt=json&prettyPrint=false": compute: Received 500 `Internal Server Error`
```

When these errors happen, they are always preceded by an error in `gke-metadata-server`:
```
[conn-id:<some_id> ip:<some_ip> pod:<some_pod> rpc-id:<some_rpc_id>] "/computeMetadata/v1/instance/service-accounts/default/token?..." HTTP/500: generic::unknown: loading: getFederatedToken("....iam.gserviceaccount.com", "", "", ....): loading: while fetching k8s token: loading: Post "https://<some_ip>/api/v1/namespaces/<namespace>/serviceaccounts/default/token": context deadline exceeded, Reason: "K8S", UserMessage: "Internal Server Error"
```

The problems started to occur last month, and our code that connects to the server has not changed.

Can you please assist us with the issue?

### Example code (or command)

```Go
import (
    "database/sql"

    "cloud.google.com/go/cloudsqlconn"
    "cloud.google.com/go/cloudsqlconn/mysql/mysql"
)

func connect() {
    cleanup, err := mysql.RegisterDriver("cloudsql-mysql", cloudsqlconn.WithCredentialsFile("key.json"))
    if err != nil {
        // ... handle error
    }
    // call cleanup when you're done with the database connection
    defer cleanup()

    db, err := sql.Open(...)
}
```
```


### Stacktrace

_No response_

### Steps to reproduce?

Connect to the CloudSQL instance, as described in the code

### Environment

1. OS type and version: alpine linux 3.17
2. Go version: 1.21
3. Cloud SQL Go Connector version: 1.6.0


### Additional Details

_No response_

**Comment by enocom** [comment]
Thanks for the issue. After you see these errors, what happens next? Is the pod useless and you have to restart it yet again?

**Comment by MarkShleiferCinemo** [comment]
Yes, after the error the pod has to restart.

**Comment by enocom** [comment]
Let me dig into this a bit. On the surface it looks like a race condition in the underlying GKE infrastructure, but I'll see if we can improve things with some retries on startup.

**Comment by enocom** [comment]
We're seeing 50x errors occasionally in our integration tests which are symptomatic of the absence retries in the refresh code. I think we'll add some retry code around the API calls to resolve this.
