### ISSUE TITLE
Add context parameter to debug logger interface

### ISSUE THREAD

**Issue by torkelrogstad** [GoogleCloudPlatform/cloud-sql-go-connector#796]
### Feature Description

It would be a good idea to add a context parameter to the `debug.Logger` interface. 

```go
type Logger interface {
	Debugf(ctx context.Context, format string, args ...interface{})
}
```

This would allow users to correlate logs with metadata that's stored in the context, like for example tracing IDs. 

This would be a breaking change. If that's an issue, we could add a new interface, `debug.ContextLogger`. This would be paired with a new option, `cloudsqlconn.WithContextDebugLogger`.

**Comment by jackwotherspoon** [comment]
Thanks again @torkelrogstad for the great PR ! 👏  We always greatly appreciate contributions 😄
